# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "bids", :force => true do |t|
    t.column "post_id", :integer
    t.column "user_id", :integer
    t.column "amount", :integer, :limit => 6
  end

  create_table "bills", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "name_on_card", :string, :limit => 100, :default => "", :null => false
    t.column "street_address", :string, :limit => 100, :default => "", :null => false
    t.column "city", :string, :limit => 100, :default => "", :null => false
    t.column "state", :string, :limit => 2, :default => "", :null => false
    t.column "zip_code", :integer, :limit => 5
    t.column "cc_type", :string, :limit => 20, :default => "", :null => false
    t.column "cc_number", :integer, :limit => 20
    t.column "cc_exp_month", :integer, :limit => 2
    t.column "cc_exp_year", :integer, :limit => 2
  end

  create_table "feedbacks", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "bidder_id", :integer, :default => 0, :null => false
    t.column "post_id", :integer, :default => 0, :null => false
    t.column "comment", :string, :limit => 150, :default => "", :null => false
    t.column "rated", :integer, :limit => 2, :default => 0, :null => false
    t.column "sent", :timestamp
  end

  create_table "messages", :force => true do |t|
    t.column "sender_id", :integer, :default => 0, :null => false
    t.column "receiver_id", :integer, :default => 0, :null => false
    t.column "subject", :string, :default => "", :null => false
    t.column "body", :text, :default => "", :null => false
    t.column "post_id", :integer, :default => 0, :null => false
    t.column "is_read", :integer, :limit => 2, :default => 0, :null => false
    t.column "time_sent", :timestamp
  end

  create_table "posts", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "title", :string, :limit => 100, :default => "", :null => false
    t.column "body", :text, :default => "", :null => false
    t.column "city", :string
    t.column "state", :string, :default => "", :null => false
    t.column "recurring", :integer, :limit => 2, :default => 0, :null => false
    t.column "frequency", :string, :limit => 10, :default => "", :null => false
    t.column "cap", :integer, :limit => 6
    t.column "category", :string, :default => "", :null => false
    t.column "end_date", :date, :null => false
    t.column "pic_1", :string, :limit => 100, :default => "", :null => false
    t.column "pic_2", :string, :limit => 100, :default => "", :null => false
    t.column "pic_3", :string, :limit => 100, :default => "", :null => false
    t.column "date_posted", :timestamp
    t.column "lowest_bid", :integer
    t.column "winner", :integer, :default => 0, :null => false
    t.column "winning_bid", :integer
    t.column "accepted", :integer, :limit => 2, :default => 0, :null => false
    t.column "left_feedback", :integer, :default => 0, :null => false
    t.column "delete_id", :integer, :default => 0, :null => false
    t.column "bidder_delete_id", :integer, :default => 0, :null => false
  end

  add_index "posts", ["winner"], :name => "winner"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "users", :force => true do |t|
    t.column "login", :string, :limit => 80
    t.column "password", :string, :limit => 40
    t.column "email_address", :string, :limit => 50, :default => "", :null => false
    t.column "phone_number", :string, :limit => 14
    t.column "first_name", :string, :limit => 25, :default => "", :null => false
    t.column "conf_code", :string
    t.column "confirmed", :integer, :limit => 2, :default => 0, :null => false
    t.column "opened_settings", :integer, :limit => 2, :default => 0, :null => false
    t.column "zip_code", :integer, :limit => 5
    t.column "user_info", :text, :default => "", :null => false
    t.column "pic", :string, :limit => 100, :default => "", :null => false
    t.column "site_url", :string, :limit => 100, :default => "", :null => false
    t.column "reputation_points", :integer, :limit => 7, :default => 1000, :null => false
    t.column "has_billing", :integer, :limit => 2, :default => 0, :null => false
    t.column "date_created", :timestamp
    t.column "is_admin", :integer, :limit => 2, :default => 0, :null => false
    t.column "ptp", :string, :default => "", :null => false
  end

end
